package server

import (
	"net/http"
	"os"

	"g9router/internal/auth"
	"g9router/internal/web"
)

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	registerAliases := func(handler http.HandlerFunc, paths ...string) { registerRoutes(mux, handler, paths...) }
	s.registerOpenAIRoutes(mux, registerAliases)
	s.registerProviderRoutes(mux)
	mux.HandleFunc("/healthz", s.health)
	mux.HandleFunc("/api/health", s.health)
	mux.HandleFunc("/api/init", s.initAPI)
	mux.HandleFunc("/api/version", s.versionAPI)
	mux.HandleFunc("/api/version/update", s.versionUpdateAPI)
	mux.HandleFunc("/api/locale", s.localeAPI)
	mux.HandleFunc("/api/tags", s.tagsAPI)
	mux.HandleFunc("/api/pricing", s.pricingAPI)
	mux.HandleFunc("/api/pricing/", s.pricingAPI)
	mux.HandleFunc("/api/shutdown", s.shutdownAPI)
	mux.HandleFunc("/api/version/shutdown", s.shutdownAPI)
	mux.HandleFunc("/api/translator/load", s.translatorLoadAPI)
	mux.HandleFunc("/api/translator/save", s.translatorSaveAPI)
	mux.HandleFunc("/api/translator/console-logs", s.consoleLogsAPI)
	mux.HandleFunc("/api/translator/console-logs/stream", s.consoleLogsStreamAPI)
	mux.HandleFunc("/api/pxpipe/status", s.pxpipeStatusAPI)
	mux.HandleFunc("/api/pxpipe/stats", s.pxpipeStatsAPI)
	mux.HandleFunc("/api/pxpipe/logs", s.pxpipeLogsAPI)
	mux.HandleFunc("/api/pxpipe/health", s.pxpipeHealthAPI)
	mux.HandleFunc("/api/pxpipe/install", s.pxpipeInstallAPI)
	mux.HandleFunc("/api/pxpipe/start", s.pxpipeStartAPI)
	mux.HandleFunc("/api/pxpipe/stop", s.pxpipeStopAPI)
	mux.HandleFunc("/api/pxpipe/restart", s.pxpipeRestartAPI)
	mux.HandleFunc("/api/translator/translate", s.translatorAPI)
	mux.HandleFunc("/api/translator/send", s.translatorSendAPI)
	mux.HandleFunc("/api/usage", s.usageAPI)
	mux.HandleFunc("/api/usage/logs", s.usageLogsAPI)
	mux.HandleFunc("/api/usage/request-logs", s.usageLogsAPI)
	mux.HandleFunc("/api/usage/providers", s.usageProvidersAPI)
	mux.HandleFunc("/api/usage/chart", s.usageChartAPI)
	mux.HandleFunc("/api/usage/request-details", s.usageRequestDetailsAPI)
	mux.HandleFunc("/api/usage/stats", s.usageStatsAPI)
	mux.HandleFunc("/api/usage/history", s.usageHistoryAPI)
	mux.HandleFunc("/api/usage/stream", s.usageStreamAPI)
	mux.HandleFunc("/api/usage/", s.usageResourceAPI)
	mux.HandleFunc("/api/oauth", s.oauthAPI)
	mux.HandleFunc("/api/oauth/codex/bulk-import", s.codexBulkImportAPI)
	mux.HandleFunc("/api/oauth/codex/import-token", s.codexImportTokenAPI)
	mux.HandleFunc("/api/oauth/gitlab/pat", s.gitlabPATAPI)
	mux.HandleFunc("/api/oauth/iflow/cookie", s.iflowCookieAPI)
	mux.HandleFunc("/api/oauth/kiro/api-key", s.kiroAPIKeyAPI)
	mux.HandleFunc("/api/oauth/kiro/auto-import", s.kiroAutoImportAPI)
	mux.HandleFunc("/api/oauth/kiro/social-authorize", s.kiroSocialAuthorizeAPI)
	mux.HandleFunc("/api/oauth/kiro/social-exchange", s.kiroSocialExchangeAPI)
	mux.HandleFunc("/api/oauth/kiro/import", s.kiroImportAPI)
	mux.HandleFunc("/api/oauth/kiro/import-cli-proxy", s.kiroExternalImportAPI)
	mux.HandleFunc("/api/oauth/cursor/import", s.cursorImportAPI)
	mux.HandleFunc("/api/oauth/cursor/auto-import", s.cursorAutoImportAPI)
	mux.HandleFunc("/api/oauth/github/device-code", s.githubDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/github/poll", s.githubPollAPI)
	mux.HandleFunc("/api/oauth/qwen/device-code", s.qwenDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/qwen/poll", s.qwenPollAPI)
	mux.HandleFunc("/api/oauth/kimi/device-code", s.kimiDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/kimi/poll", s.kimiPollAPI)
	mux.HandleFunc("/api/oauth/kimi-coding/device-code", s.kimiDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/kimi-coding/poll", s.kimiPollAPI)
	mux.HandleFunc("/api/oauth/gemini-cli/authorize", s.geminiAuthorizeAPI)
	mux.HandleFunc("/api/oauth/gemini-cli/exchange", s.geminiExchangeAPI)
	mux.HandleFunc("/api/oauth/antigravity/authorize", s.antigravityAuthorizeAPI)
	mux.HandleFunc("/api/oauth/antigravity/exchange", s.antigravityExchangeAPI)
	mux.HandleFunc("/api/oauth/grok-cli/device-code", s.grokCLIDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/grok-cli/poll", s.grokCLIPollAPI)
	mux.HandleFunc("/api/oauth/cline/authorize", s.clineAuthorizeAPI)
	mux.HandleFunc("/api/oauth/cline/exchange", s.clineExchangeAPI)
	mux.HandleFunc("/api/oauth/clinepass/authorize", s.clineAuthorizeAPI)
	mux.HandleFunc("/api/oauth/clinepass/exchange", s.clineExchangeAPI)
	mux.HandleFunc("/api/oauth/kilocode/device-code", s.kiloCodeDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/kilocode/poll", s.kiloCodePollAPI)
	mux.HandleFunc("/api/oauth/codebuddy-cn/device-code", s.codeBuddyDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/codebuddy-cn/poll", s.codeBuddyPollAPI)
	mux.HandleFunc("/api/oauth/kimchi/authorize", s.kimchiAuthorizeAPI)
	mux.HandleFunc("/api/oauth/kimchi/exchange", s.kimchiExchangeAPI)
	mux.HandleFunc("/api/oauth/qoder/device-code", s.qoderDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/qoder/poll", s.qoderPollAPI)
	mux.HandleFunc("/api/oauth/kiro/device-code", s.kiroDeviceCodeAPI)
	mux.HandleFunc("/api/oauth/kiro/poll", s.kiroPollAPI)
	mux.HandleFunc("/api/oauth/gitlab/authorize", s.gitlabAuthorizeAPI)
	mux.HandleFunc("/api/oauth/gitlab/exchange", s.gitlabExchangeAPI)
	mux.HandleFunc("/api/oauth/iflow/authorize", s.iflowAuthorizeAPI)
	mux.HandleFunc("/api/oauth/iflow/exchange", s.iflowExchangeAPI)
	mux.HandleFunc("/api/oauth/xai/authorize", s.xaiAuthorizeAPI)
	mux.HandleFunc("/api/oauth/xai/exchange", s.xaiExchangeAPI)
	mux.HandleFunc("/api/oauth/xai/", s.oauthProxyAPI)
	mux.HandleFunc("/api/oauth/claude/", s.genericOAuthAPI)
	mux.HandleFunc("/api/oauth/codex/", s.genericOAuthAPI)
	mux.HandleFunc("/api/oauth/", s.oauthResourceAPI)
	mux.HandleFunc("/api/provider-nodes", s.providerNodesAPI)
	mux.HandleFunc("/api/provider-nodes/validate", s.validateProviderNodeAPI)
	mux.HandleFunc("/api/provider-nodes/", s.providerNodeResourceAPI)
	mux.HandleFunc("/api/proxy-pools", s.proxyPoolsAPI)
	mux.HandleFunc("/api/proxy-pools/", s.proxyPoolResourceAPI)
	mux.HandleFunc("/api/proxy-pools/vercel-deploy", s.vercelDeployAPI)
	mux.HandleFunc("/api/proxy-pools/cloudflare-deploy", s.cloudflareDeployAPI)
	mux.HandleFunc("/api/proxy-pools/deno-deploy", s.denoDeployAPI)
	mux.HandleFunc("/api/tunnel/status", s.tunnelStatusAPI)
	mux.HandleFunc("/api/tunnel/enable", s.tunnelEnableAPI)
	mux.HandleFunc("/api/tunnel/disable", s.tunnelDisableAPI)
	mux.HandleFunc("/api/tunnel/tailscale-check", s.tailscaleCheckAPI)
	mux.HandleFunc("/api/tunnel/tailscale-enable", s.tailscaleEnableAPI)
	mux.HandleFunc("/api/tunnel/tailscale-disable", s.tailscaleDisableAPI)
	mux.HandleFunc("/api/tunnel/tailscale-install", s.tailscaleInstallAPI)
	mux.HandleFunc("/api/media-providers/tts/voices", s.ttsVoicesAPI)
	mux.HandleFunc("/api/media-providers/tts/deepgram/voices", s.specializedVoicesAPI)
	mux.HandleFunc("/api/media-providers/tts/elevenlabs/voices", s.specializedVoicesAPI)
	mux.HandleFunc("/api/media-providers/tts/inworld/voices", s.specializedVoicesAPI)
	mux.HandleFunc("/api/media-providers/tts/minimax/voices", s.specializedVoicesAPI)
	mux.HandleFunc("/api/keys", s.keysAPI)
	mux.HandleFunc("/api/keys/", s.keyResourceAPI)
	mux.HandleFunc("/api/combos", s.combosAPI)
	mux.HandleFunc("/api/combos/", s.comboResourceAPI)
	mux.HandleFunc("/api/settings", s.settingsAPI)
	mux.HandleFunc("/api/settings/proxy-test", s.proxyTestAPI)
	mux.HandleFunc("/api/settings/require-login", s.requireLoginAPI)
	mux.HandleFunc("/api/settings/database", s.databaseSettingsAPI)
	mux.HandleFunc("/api/models/alias", s.modelAliasAPI)
	mux.HandleFunc("/api/models", s.modelsAPI)
	mux.HandleFunc("/api/models/custom", s.customModelsAPI)
	mux.HandleFunc("/api/models/disabled", s.disabledModelsAPI)
	mux.HandleFunc("/api/models/availability", s.modelsAvailabilityAPI)
	mux.HandleFunc("/api/models/test", s.modelTestAPI)
	mux.HandleFunc("/api/cli-tools/all-statuses", s.cliToolsStatusAPI)
	mux.HandleFunc("/api/cli-tools/guides", s.cliToolsGuidesAPI)
	mux.HandleFunc("/api/cli-tools/antigravity-mitm/alias", s.antigravityAliasAPI)
	mux.HandleFunc("/api/cli-tools/antigravity-mitm", s.antigravityMITMAPI)
	mux.HandleFunc("/api/cli-tools/claude-settings", s.claudeSettingsAPI)
	mux.HandleFunc("/api/cli-tools/codex-settings", s.codexSettingsAPI)
	mux.HandleFunc("/api/cli-tools/opencode-settings", s.opencodeSettingsAPI)
	mux.HandleFunc("/api/cli-tools/copilot-settings", s.copilotSettingsAPI)
	mux.HandleFunc("/api/cli-tools/droid-settings", s.droidSettingsAPI)
	mux.HandleFunc("/api/cli-tools/cline-settings", s.clineSettingsAPI)
	mux.HandleFunc("/api/cli-tools/kilo-settings", s.kiloSettingsAPI)
	mux.HandleFunc("/api/cli-tools/openclaw-settings", s.openclawSettingsAPI)
	mux.HandleFunc("/api/cli-tools/deepseek-tui-settings", s.deepSeekTUISettingsAPI)
	mux.HandleFunc("/api/cli-tools/grok-build-settings", s.grokBuildSettingsAPI)
	mux.HandleFunc("/api/cli-tools/hermes-settings", s.hermesSettingsAPI)
	mux.HandleFunc("/api/cli-tools/jcode-settings", s.jcodeSettingsAPI)
	mux.HandleFunc("/api/cli-tools/cowork-mcp-registry", s.coworkMCPRegistryAPI)
	mux.HandleFunc("/api/cli-tools/cowork-mcp-tools", s.coworkMCPToolsAPI)
	mux.HandleFunc("/api/cli-tools/cowork-settings", s.coworkSettingsAPI)
	mux.HandleFunc("/api/mcp/", s.mcpAPI)
	mux.HandleFunc("/api/headroom/status", s.headroomStatusAPI)
	mux.HandleFunc("/api/headroom/start", s.headroomStartAPI)
	mux.HandleFunc("/api/headroom/stop", s.headroomStopAPI)
	mux.HandleFunc("/api/headroom/restart", s.headroomRestartAPI)
	mux.HandleFunc("/api/headroom/proxy/", s.headroomProxyAPI)
	mux.HandleFunc("/api/headroom/extras", s.headroomExtrasAPI)
	mux.HandleFunc("/api/auth/status", s.authStatus)
	mux.HandleFunc("/api/auth/login", s.authLogin)
	mux.HandleFunc("/api/auth/logout", s.authLogout)
	mux.HandleFunc("/api/auth/reset-password", s.resetPasswordAPI)
	mux.HandleFunc("/api/auth/oidc/start", s.oidcStart)
	mux.HandleFunc("/api/auth/oidc/callback", s.oidcCallback)
	mux.HandleFunc("/api/auth/oidc/test", s.oidcTestAPI)
	if s.options.WebUI {
		mux.Handle("/", web.Handler())
	}
	handler := logging(mux)
	_, passwordConfigured := s.settings.Secret("password")
	loginRequired := s.keys.HasActive() || os.Getenv("G9ROUTER_PASSWORD") != "" || passwordConfigured
	return auth.MiddlewareWithSession(handler, os.Getenv("G9ROUTER_ADMIN_KEY"), s.keys.Valid, loginRequired, s.sessions)
}

func registerRoutes(mux *http.ServeMux, handler http.HandlerFunc, paths ...string) {
	for _, path := range paths {
		mux.HandleFunc(path, handler)
	}
}

func (s *Server) registerOpenAIRoutes(mux *http.ServeMux, aliases func(http.HandlerFunc, ...string)) {
	aliases(s.models, "/v1/models", "/api/v1/models", "/v1", "/api/v1")
	aliases(s.modelCatalogAPI, "/v1/models/", "/api/v1/models/")
	mux.HandleFunc("/v1beta/models", s.betaModels)
	mux.HandleFunc("/v1beta/models/", s.betaModelResource)
	mux.HandleFunc("/api/v1beta/models", s.betaModels)
	mux.HandleFunc("/api/v1beta/models/", s.betaModelResource)
	aliases(s.chatCompletions, "/v1/chat/completions", "/api/v1/chat/completions", "/api/dashboard/chat/completions")
	aliases(s.responses, "/v1/responses", "/api/v1/responses")
	aliases(s.responsesCompactAPI, "/v1/responses/compact", "/api/v1/responses/compact")
	aliases(s.ollamaChatAPI, "/v1/api/chat", "/api/v1/api/chat")
	aliases(s.messages, "/v1/messages", "/api/v1/messages")
	aliases(s.countTokensAPI, "/v1/messages/count_tokens", "/api/v1/messages/count_tokens")
	aliases(s.embeddings, "/v1/embeddings", "/api/v1/embeddings")
	aliases(s.images, "/v1/images/generations", "/api/v1/images/generations")
	aliases(s.transcriptions, "/v1/audio/transcriptions", "/api/v1/audio/transcriptions")
	aliases(s.speech, "/v1/audio/speech", "/api/v1/audio/speech")
	aliases(s.audioVoicesAPI, "/v1/audio/voices", "/api/v1/audio/voices")
	aliases(s.search, "/v1/search", "/api/v1/search")
	aliases(s.videoAPI, "/v1/videos/", "/api/v1/videos/")
	aliases(s.webFetchAPI, "/v1/web/fetch", "/api/v1/web/fetch")
}

func (s *Server) registerProviderRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/providers", s.providerAPI)
	mux.HandleFunc("/api/providers/validate", s.validateProviderAPI)
	mux.HandleFunc("/api/providers/test-batch", s.providerBatchTestAPI)
	mux.HandleFunc("/api/providers/suggested-models", s.suggestedModelsAPI)
	mux.HandleFunc("/api/providers/", s.providerResourceAPI)
	mux.HandleFunc("/api/providers/client", s.providerClientAPI)
	mux.HandleFunc("/api/providers/kilo/free-models", s.kiloFreeModelsAPI)
}
