package providers

func init() {
	for id, descriptor := range map[string]Descriptor{
		"deepseek":       {ID: "deepseek", Alias: "deepseek", BaseURL: "https://api.deepseek.com/chat/completions", Format: "openai", Services: []string{"llm"}},
		"mistral":        {ID: "mistral", Alias: "mistral", BaseURL: "https://api.mistral.ai/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding"}},
		"cohere":         {ID: "cohere", Alias: "cohere", BaseURL: "https://api.cohere.com/v2/chat", Format: "openai", Services: []string{"llm", "embedding"}},
		"cerebras":       {ID: "cerebras", Alias: "cerebras", BaseURL: "https://api.cerebras.ai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"together":       {ID: "together", Alias: "together", BaseURL: "https://api.together.xyz/v1/chat/completions", Format: "openai", Services: []string{"llm", "imageToText"}},
		"fireworks":      {ID: "fireworks", Alias: "fireworks", BaseURL: "https://api.fireworks.ai/inference/v1/chat/completions", Format: "openai", Services: []string{"llm", "imageToText"}},
		"siliconflow":    {ID: "siliconflow", Alias: "siliconflow", BaseURL: "https://api.siliconflow.cn/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding", "image"}},
		"nebius":         {ID: "nebius", Alias: "nebius", BaseURL: "https://api.studio.nebius.ai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"hyperbolic":     {ID: "hyperbolic", Alias: "hyperbolic", BaseURL: "https://api.hyperbolic.xyz/v1/chat/completions", Format: "openai", Services: []string{"llm", "image"}},
		"chutes":         {ID: "chutes", Alias: "chutes", BaseURL: "https://llm.chutes.ai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"venice":         {ID: "venice", Alias: "venice", BaseURL: "https://api.venice.ai/api/v1/chat/completions", Format: "openai", Services: []string{"llm", "image"}},
		"glm":            {ID: "glm", Alias: "glm", BaseURL: "https://open.bigmodel.cn/api/paas/v4/chat/completions", Format: "openai", Services: []string{"llm", "imageToText"}},
		"glm-cn":         {ID: "glm-cn", Alias: "glm-cn", BaseURL: "https://open.bigmodel.cn/api/paas/v4/chat/completions", Format: "openai", Services: []string{"llm", "imageToText"}},
		"byteplus":       {ID: "byteplus", Alias: "byteplus", BaseURL: "https://ark.cn-beijing.volces.com/api/v3/chat/completions", Format: "openai", Services: []string{"llm", "image"}},
		"volcengine-ark": {ID: "volcengine-ark", Alias: "volcengine-ark", BaseURL: "https://ark.cn-beijing.volces.com/api/v3/chat/completions", Format: "openai", Services: []string{"llm", "image"}},
		"alicode":        {ID: "alicode", Alias: "alicode", BaseURL: "https://coding.dashscope.aliyuncs.com/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"alicode-intl":   {ID: "alicode-intl", Alias: "alicode-intl", BaseURL: "https://coding-intl.dashscope.aliyuncs.com/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"alims-intl":     {ID: "alims-intl", Alias: "alims-intl", BaseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions", Format: "openai", Services: []string{"llm", "image"}},
		"jina-ai":        {ID: "jina-ai", Alias: "jina", BaseURL: "https://api.jina.ai/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding"}},
		"opencode":       {ID: "opencode", Alias: "oc", BaseURL: "https://api.opencode.ai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"opencode-go":    {ID: "opencode-go", Alias: "opencode-go", BaseURL: "https://opencode.ai/zen/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"kimchi":         {ID: "kimchi", Alias: "kimchi", BaseURL: "https://llm.kimchi.dev/openai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"mimo-free":      {ID: "mimo-free", Alias: "mmf", BaseURL: "https://api.xiaomimimo.com/api/free-ai/openai/chat", Format: "openai", Services: []string{"llm"}},
		"minimax-cn":     {ID: "minimax-cn", Alias: "minimax-cn", BaseURL: "https://api.minimaxi.com/v1/text/chatcompletion_v2", Format: "openai", Services: []string{"llm", "tts", "image"}},
		"firecrawl":      {ID: "firecrawl", Alias: "firecrawl", BaseURL: "https://api.firecrawl.dev/v1/scrape", Format: "firecrawl", Services: []string{"webFetch"}},
		"jina-reader":    {ID: "jina-reader", Alias: "jina-reader", BaseURL: "https://r.jina.ai", Format: "jina-reader", Services: []string{"webFetch"}},
		"playht":         {ID: "playht", Alias: "playht", BaseURL: "https://api.play.ht/api/v2/tts/stream", Format: "playht", Services: []string{"tts"}},
		"cartesia":       {ID: "cartesia", Alias: "cartesia", BaseURL: "https://api.cartesia.ai/tts/bytes", Format: "cartesia", Services: []string{"tts"}},
		"coqui":          {ID: "coqui", Alias: "coqui", BaseURL: "http://localhost:5002/api/tts", Format: "coqui", Services: []string{"tts"}},
		"inworld":        {ID: "inworld", Alias: "inworld", BaseURL: "https://api.inworld.ai/tts/v1/voice", Format: "inworld", Services: []string{"tts"}},
		"tortoise":       {ID: "tortoise", Alias: "tortoise", BaseURL: "http://localhost:5000/api/tts", Format: "tortoise", Services: []string{"tts"}},
		"aws-polly":      {ID: "aws-polly", Alias: "aws-polly", BaseURL: "https://polly.{region}.amazonaws.com/v1/speech", Format: "aws-polly", Services: []string{"tts"}},
		"google-tts":     {ID: "google-tts", Alias: "google-tts", BaseURL: "google-tts", Format: "google-tts", Services: []string{"tts"}},
		"local-device":   {ID: "local-device", Alias: "local-device", BaseURL: "local-device", Format: "local-device", Services: []string{"tts"}},
		"blackbox":       {ID: "blackbox", Alias: "blackbox", BaseURL: "https://api.blackbox.ai/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"commandcode":    {ID: "commandcode", Alias: "commandcode", BaseURL: "https://api.commandcode.ai/alpha/generate", Format: "commandcode", Services: []string{"llm"}},
		"grok-web":       {ID: "grok-web", Alias: "grok-web", BaseURL: "https://grok.com/rest/app-chat/conversations/new", Format: "grok-web", Services: []string{"llm"}},
		"kilocode":       {ID: "kilocode", Alias: "kc", BaseURL: "https://api.kilo.ai/api/openrouter/chat/completions", Format: "openai", Services: []string{"llm"}},
		"vertex-partner": {ID: "vertex-partner", Alias: "vertex-partner", BaseURL: "https://aiplatform.googleapis.com", Format: "vertex", Services: []string{"llm", "imageToText"}},
		"voyage-ai":      {ID: "voyage-ai", Alias: "voyage-ai", BaseURL: "https://api.voyageai.com/v1/embeddings", Format: "voyage-ai", Services: []string{"embedding"}},
		"topaz":          {ID: "topaz", Alias: "topaz", BaseURL: "https://api.topazlabs.com/image/v1/enhance", Format: "topaz", Services: []string{"image"}},
		"mmf":            {ID: "mmf", Alias: "mmf", BaseURL: "https://api.xiaomimimo.com/api/free-ai/openai/chat", Format: "openai", Services: []string{"llm"}},
		"claude":         {ID: "claude", Alias: "cc", BaseURL: "https://api.anthropic.com/v1/messages", Format: "claude", Services: []string{"llm", "imageToText"}},
		"gemini-cli":     {ID: "gemini-cli", Alias: "gemini-cli", BaseURL: "https://cloudcode-pa.googleapis.com/v1internal", Format: "gemini-cli", Services: []string{"llm", "imageToText"}},
		"gitlab":         {ID: "gitlab", Alias: "gitlab", BaseURL: "https://gitlab.com/api/v4/chat/completions", Format: "openai", Services: []string{"llm"}},
		"iflow":          {ID: "iflow", Alias: "iflow", BaseURL: "https://apis.iflow.cn/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"grok-cli":       {ID: "grok-cli", Alias: "gcli", BaseURL: "https://cli-chat-proxy.grok.com/v1/responses", Format: "openai-responses", Services: []string{"llm"}},
		"antigravity":    {ID: "antigravity", Alias: "ag", BaseURL: "https://cloudcode-pa.googleapis.com", Format: "antigravity", Services: []string{"llm", "image", "imageToText"}},
		"cline":          {ID: "cline", Alias: "cline", BaseURL: "https://api.cline.bot/api/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"clinepass":      {ID: "clinepass", Alias: "clinepass", BaseURL: "https://api.cline.bot/api/v1/chat/completions", Format: "openai", Services: []string{"llm"}},
		"codebuddy-cn":   {ID: "codebuddy-cn", Alias: "codebuddy-cn", BaseURL: "https://copilot.tencent.com/v2/chat/completions", Format: "openai", Services: []string{"llm"}},
		"azure":          {ID: "azure", Alias: "azure", BaseURL: "", Format: "openai", Services: []string{"llm", "embedding", "image", "tts", "stt"}},
		"comfyui":        {ID: "comfyui", Alias: "comfyui", BaseURL: "http://localhost:8188", Format: "comfyui", Services: []string{"image"}, Models: []Model{{ID: "flux-dev", Name: "FLUX Dev", Kind: "image"}, {ID: "sdxl", Name: "SDXL", Kind: "image"}}},
	} {
		if _, exists := Registry[id]; !exists {
			Registry[id] = descriptor
		}
	}
}
