package providers

func init() {
	for id, descriptor := range map[string]Descriptor{
		"openrouter":        {ID: "openrouter", Alias: "openrouter", BaseURL: "https://openrouter.ai/api/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding", "tts", "image", "imageToText"}, Models: []Model{{ID: "openai/text-embedding-3-large", Name: "OpenAI Text Embedding 3 Large", Kind: "embedding"}, {ID: "openai/text-embedding-3-small", Name: "OpenAI Text Embedding 3 Small", Kind: "embedding"}, {ID: "openai/text-embedding-ada-002", Name: "OpenAI Text Embedding Ada 002", Kind: "embedding"}, {ID: "qwen/qwen3-embedding-8b", Name: "Qwen3 Embedding 8B", Kind: "embedding"}, {ID: "perplexity/pplx-embed-v1-4b", Name: "Perplexity Embed V1 4B", Kind: "embedding"}, {ID: "perplexity/pplx-embed-v1-0.6b", Name: "Perplexity Embed V1 0.6B", Kind: "embedding"}, {ID: "nvidia/llama-nemotron-embed-vl-1b-v2:free", Name: "NVIDIA Nemotron Embed VL 1B V2 (Free)", Kind: "embedding"}, {ID: "openai/gpt-4o-mini-tts", Name: "GPT-4o Mini TTS", Kind: "tts"}, {ID: "openai/tts-1-hd", Name: "TTS-1 HD", Kind: "tts"}, {ID: "openai/tts-1", Name: "TTS-1", Kind: "tts"}, {ID: "openai/dall-e-3", Name: "DALL-E 3 (via OpenRouter)", Kind: "image"}, {ID: "openai/gpt-image-1", Name: "GPT Image 1 (via OpenRouter)", Kind: "image"}, {ID: "google/imagen-3.0-generate-002", Name: "Imagen 3 (via OpenRouter)", Kind: "image"}, {ID: "black-forest-labs/FLUX.1-schnell", Name: "FLUX.1 Schnell (via OpenRouter)", Kind: "image"}}},
		"minimax":           {ID: "minimax", Alias: "minimax", BaseURL: "https://api.minimax.io/v1/chat/completions", Format: "openai", Services: []string{"llm", "image", "tts", "imageToText", "webSearch"}, Models: []Model{{ID: "MiniMax-M3", Name: "MiniMax M3"}, {ID: "MiniMax-M2.7", Name: "MiniMax M2.7"}, {ID: "MiniMax-M2.5", Name: "MiniMax M2.5"}, {ID: "MiniMax-M2.1", Name: "MiniMax M2.1"}, {ID: "minimax-image-01", Name: "MiniMax Image 01", Kind: "image"}, {ID: "speech-2.8-hd", Name: "Speech 2.8 HD", Kind: "tts"}, {ID: "speech-2.8-turbo", Name: "Speech 2.8 Turbo", Kind: "tts"}, {ID: "speech-2.6-hd", Name: "Speech 2.6 HD", Kind: "tts"}, {ID: "speech-2.6-turbo", Name: "Speech 2.6 Turbo", Kind: "tts"}, {ID: "speech-02-hd", Name: "Speech 02 HD", Kind: "tts"}, {ID: "speech-02-turbo", Name: "Speech 02 Turbo", Kind: "tts"}, {ID: "speech-01-hd", Name: "Speech 01 HD", Kind: "tts"}, {ID: "speech-01-turbo", Name: "Speech 01 Turbo", Kind: "tts"}}},
		"recraft":           {ID: "recraft", Alias: "recraft", BaseURL: "https://external.api.recraft.ai/v1/images/generations", Format: "openai", Services: []string{"image"}, Models: []Model{{ID: "recraftv3", Name: "Recraft V3", Kind: "image"}}},
		"vercel-ai-gateway": {ID: "vercel-ai-gateway", Alias: "vercel-ai-gateway", BaseURL: "https://ai-gateway.vercel.sh/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding", "image", "imageToText", "webSearch"}},
		"xai":               {ID: "xai", Alias: "xai", BaseURL: "https://api.x.ai/v1/chat/completions", Format: "openai", Services: []string{"llm", "image", "video", "imageToText", "webSearch"}, Models: []Model{{ID: "grok-4", Name: "Grok 4"}, {ID: "grok-2-image-1212", Name: "Grok 2 Image", Kind: "image"}, {ID: "grok-imagine-video", Name: "Grok Imagine Video", Kind: "video"}}},
		"groq":              {ID: "groq", Alias: "groq", BaseURL: "https://api.groq.com/openai/v1/chat/completions", Format: "openai", Services: []string{"llm", "imageToText", "stt"}, Models: []Model{{ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B"}, {ID: "whisper-large-v3", Name: "Whisper Large v3", Kind: "stt"}}},
		"ollama":            {ID: "ollama", Alias: "ollama", BaseURL: "https://ollama.com/api/chat", Format: "ollama", Services: []string{"llm"}},
		"qwen":              {ID: "qwen", Alias: "qwen", BaseURL: "https://portal.qwen.ai/v1/chat/completions", Format: "openai", Services: []string{"llm", "imageToText"}, Models: []Model{{ID: "qwen3-coder-plus", Name: "Qwen3 Coder Plus"}, {ID: "qwen3-coder-flash", Name: "Qwen3 Coder Flash"}}},
		"kimi":              {ID: "kimi", Alias: "kimi", BaseURL: "https://api.kimi.com/coding/v1/chat/completions", Format: "openai", Services: []string{"llm", "webSearch"}, Models: []Model{{ID: "kimi-k3", Name: "Kimi K3"}, {ID: "k3", Name: "Kimi K3 (Code)"}, {ID: "kimi-for-coding", Name: "Kimi for Coding"}, {ID: "kimi-for-coding-highspeed", Name: "Kimi for Coding Highspeed"}, {ID: "kimi-k2.7-code", Name: "Kimi K2.7 Code"}, {ID: "kimi-k2.7-code-highspeed", Name: "Kimi K2.7 Code Highspeed"}, {ID: "kimi-k2.6", Name: "Kimi K2.6"}, {ID: "kimi-k2.5", Name: "Kimi K2.5"}, {ID: "kimi-k2.5-thinking", Name: "Kimi K2.5 Thinking"}, {ID: "kimi-latest", Name: "Kimi Latest"}}},
		"qoder":             {ID: "qoder", Alias: "qoder", BaseURL: "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation", Format: "qoder", Services: []string{"llm"}, Models: []Model{{ID: "qmodel_latest", Name: "Qoder Qwen 3.7 Max"}}},
		"tavily":            {ID: "tavily", Alias: "tavily", BaseURL: "https://api.tavily.com/search", Format: "tavily", Services: []string{"webSearch"}},
		"brave-search":      {ID: "brave-search", Alias: "brave-search", BaseURL: "https://api.search.brave.com/res/v1", Format: "brave-search", Services: []string{"webSearch"}},
		"exa":               {ID: "exa", Alias: "exa", BaseURL: "https://api.exa.ai/search", Format: "exa", Services: []string{"webSearch"}},
		"serper":            {ID: "serper", Alias: "serper", BaseURL: "https://google.serper.dev", Format: "serper", Services: []string{"webSearch"}},
		"google-pse":        {ID: "google-pse", Alias: "google-pse", BaseURL: "https://www.googleapis.com/customsearch/v1", Format: "google-pse", Services: []string{"webSearch"}},
		"searxng":           {ID: "searxng", Alias: "searxng", BaseURL: "http://localhost:8080/search", Format: "searxng", Services: []string{"webSearch"}},
		"perplexity":        {ID: "perplexity", Alias: "perplexity", BaseURL: "https://api.perplexity.ai/chat/completions", Format: "openai", Services: []string{"llm", "webSearch"}, Models: []Model{{ID: "sonar-pro", Name: "Sonar Pro"}, {ID: "sonar", Name: "Sonar"}}},
		"linkup":            {ID: "linkup", Alias: "linkup", BaseURL: "https://api.linkup.so/v1/search", Format: "linkup", Services: []string{"webSearch"}},
		"searchapi":         {ID: "searchapi", Alias: "searchapi", BaseURL: "https://www.searchapi.io/api/v1/search", Format: "searchapi", Services: []string{"webSearch"}},
		"youcom":            {ID: "youcom", Alias: "youcom", BaseURL: "https://ydc-index.io/v1/search", Format: "youcom", Services: []string{"webSearch"}},
		"deepgram":          {ID: "deepgram", Alias: "deepgram", BaseURL: "https://api.deepgram.com/v1/listen", Format: "deepgram", Services: []string{"stt"}, Models: []Model{{ID: "nova-3", Name: "Nova 3", Kind: "stt"}, {ID: "nova-2", Name: "Nova 2", Kind: "stt"}}},
		"assemblyai":        {ID: "assemblyai", Alias: "assemblyai", BaseURL: "https://api.assemblyai.com/v2/transcript", Format: "assemblyai", Services: []string{"stt"}, Models: []Model{{ID: "universal-3-pro", Name: "Universal 3 Pro", Kind: "stt"}, {ID: "universal-2", Name: "Universal 2", Kind: "stt"}}},
		"nvidia":            {ID: "nvidia", Alias: "nvidia", BaseURL: "https://integrate.api.nvidia.com/v1/chat/completions", Format: "openai", Services: []string{"stt", "tts", "embedding"}, Models: []Model{{ID: "nvidia/parakeet-ctc-1.1b-asr", Name: "Parakeet CTC 1.1B", Kind: "stt"}, {ID: "fastpitch", Name: "FastPitch", Kind: "tts"}}},
		"huggingface":       {ID: "huggingface", Alias: "huggingface", BaseURL: "https://api-inference.huggingface.co/models", Format: "huggingface", Services: []string{"stt", "image"}},
		"stability-ai":      {ID: "stability-ai", Alias: "stability-ai", BaseURL: "https://api.stability.ai/v2beta/stable-image/generate", Format: "stability-ai", Services: []string{"image"}, Models: []Model{{ID: "stable-image-ultra", Name: "Stable Image Ultra", Kind: "image"}, {ID: "stable-image-core", Name: "Stable Image Core", Kind: "image"}}},
		"cloudflare-ai":     {ID: "cloudflare-ai", Alias: "cloudflare-ai", BaseURL: "https://api.cloudflare.com/client/v4/accounts", Format: "cloudflare-ai", Services: []string{"llm", "image"}, Models: []Model{{ID: "@cf/meta/llama-3.2-1b-instruct", Name: "Llama 3.2 1B Instruct"}, {ID: "@cf/meta/llama-3.2-3b-instruct", Name: "Llama 3.2 3B Instruct"}, {ID: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", Name: "Llama 3.1 8B Instruct FP8 Fast"}, {ID: "@cf/meta/llama-3.1-8b-instruct-awq", Name: "Llama 3.1 8B Instruct AWQ"}, {ID: "@cf/mistralai/mistral-small-3.1-24b-instruct", Name: "Mistral Small 3.1 24B Instruct"}, {ID: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", Name: "Llama 3.1 70B Instruct FP8 Fast"}, {ID: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", Name: "Llama 3.3 70B Instruct FP8 Fast"}, {ID: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", Name: "DeepSeek R1 Distill Qwen 32B"}, {ID: "@cf/moonshotai/kimi-k2.5", Name: "Kimi K2.5"}, {ID: "@cf/moonshotai/kimi-k2.6", Name: "Kimi K2.6"}, {ID: "@cf/zai-org/glm-4.7-flash", Name: "GLM 4.7 Flash"}, {ID: "@cf/qwen/qwq-32b", Name: "QwQ 32B"}, {ID: "@cf/qwen/qwen2.5-coder-32b-instruct", Name: "Qwen 2.5 Coder 32B Instruct"}, {ID: "@cf/black-forest-labs/flux-2-klein-9b", Name: "FLUX.2 Klein 9B", Kind: "image"}, {ID: "@cf/black-forest-labs/flux-2-klein-4b", Name: "FLUX.2 Klein 4B", Kind: "image"}, {ID: "@cf/black-forest-labs/flux-2-dev", Name: "FLUX.2 Dev", Kind: "image"}, {ID: "@cf/leonardo/lucid-origin", Name: "Lucid Origin", Kind: "image"}, {ID: "@cf/leonardo/phoenix-1.0", Name: "Phoenix 1.0", Kind: "image"}, {ID: "@cf/black-forest-labs/flux-1-schnell", Name: "FLUX.1 Schnell", Kind: "image"}, {ID: "@cf/bytedance/stable-diffusion-xl-lightning", Name: "SDXL Lightning", Kind: "image"}, {ID: "@cf/lykon/dreamshaper-8-lcm", Name: "DreamShaper 8 LCM", Kind: "image"}, {ID: "@cf/runwayml/stable-diffusion-v1-5-img2img", Name: "Stable Diffusion v1.5 Img2Img", Kind: "image"}, {ID: "@cf/runwayml/stable-diffusion-v1-5-inpainting", Name: "Stable Diffusion v1.5 Inpainting", Kind: "image"}, {ID: "@cf/stabilityai/stable-diffusion-xl-base-1.0", Name: "SDXL Base 1.0", Kind: "image"}}},
		"fal-ai":            {ID: "fal-ai", Alias: "fal-ai", BaseURL: "https://queue.fal.run", Format: "fal-ai", Services: []string{"image"}, Models: []Model{{ID: "fal-ai/flux/schnell", Name: "FLUX Schnell", Kind: "image"}, {ID: "fal-ai/flux/dev", Name: "FLUX Dev", Kind: "image"}}},
		"black-forest-labs": {ID: "black-forest-labs", Alias: "black-forest-labs", BaseURL: "https://api.bfl.ai/v1", Format: "black-forest-labs", Services: []string{"image"}, Models: []Model{{ID: "flux-pro-1.1", Name: "FLUX Pro 1.1", Kind: "image"}}},
		"runwayml":          {ID: "runwayml", Alias: "runwayml", BaseURL: "https://api.dev.runwayml.com/v1", Format: "runwayml", Services: []string{"image", "video"}, Models: []Model{{ID: "gen4_image", Name: "Gen-4 Image", Kind: "image"}}},
		"sdwebui":           {ID: "sdwebui", Alias: "sdwebui", BaseURL: "http://localhost:7860/sdapi/v1/txt2img", Format: "sdwebui", Services: []string{"image"}},
		"nanobanana":        {ID: "nanobanana", Alias: "nanobanana", BaseURL: "https://api.nanobananaapi.ai/api/v1/nanobanana/generate", Format: "nanobanana", Services: []string{"image"}, Models: []Model{{ID: "nanobanana-flash", Name: "NanoBanana Flash", Kind: "image"}, {ID: "nanobanana-pro", Name: "NanoBanana Pro", Kind: "image"}}},
	} {
		if _, exists := Registry[id]; !exists {
			Registry[id] = descriptor
		}
	}
}
