package providers

type Descriptor struct {
	ID, Alias, BaseURL, Format string
	Headers                    map[string]string
	Services                   []string
	Models                     []Model
}
type Model struct {
	ID, Name, Kind string
	Params         []string
}

var Registry = map[string]Descriptor{
	"openai":    {ID: "openai", Alias: "openai", BaseURL: "https://api.openai.com/v1/chat/completions", Format: "openai", Services: []string{"llm", "embedding", "tts", "stt", "image", "imageToText", "webSearch"}, Models: []Model{{ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "gpt-5.4-nano", Name: "GPT-5.4 Nano"}, {ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gpt-5.1", Name: "GPT-5.1"}, {ID: "gpt-5", Name: "GPT-5"}, {ID: "gpt-5-mini", Name: "GPT-5 Mini"}, {ID: "gpt-5-nano", Name: "GPT-5 Nano"}, {ID: "gpt-4o", Name: "GPT-4o"}, {ID: "gpt-4o-mini", Name: "GPT-4o Mini"}, {ID: "gpt-4-turbo", Name: "GPT-4 Turbo"}, {ID: "gpt-4.1", Name: "GPT-4.1"}, {ID: "gpt-4.1-mini", Name: "GPT-4.1 Mini"}, {ID: "gpt-4.1-nano", Name: "GPT-4.1 Nano"}, {ID: "o3", Name: "O3"}, {ID: "o3-mini", Name: "O3 Mini"}, {ID: "o3-pro", Name: "O3 Pro"}, {ID: "o4-mini", Name: "O4 Mini"}, {ID: "o1", Name: "O1"}, {ID: "o1-mini", Name: "O1 Mini"}, {ID: "text-embedding-3-large", Name: "Text Embedding 3 Large", Kind: "embedding"}, {ID: "text-embedding-3-small", Name: "Text Embedding 3 Small", Kind: "embedding"}, {ID: "text-embedding-ada-002", Name: "Text Embedding Ada 002", Kind: "embedding"}, {ID: "tts-1", Name: "TTS-1", Kind: "tts"}, {ID: "tts-1-hd", Name: "TTS-1 HD", Kind: "tts"}, {ID: "gpt-4o-mini-tts", Name: "GPT-4o Mini TTS", Kind: "tts"}, {ID: "whisper-1", Name: "Whisper 1", Kind: "stt"}, {ID: "gpt-4o-transcribe", Name: "GPT-4o Transcribe", Kind: "stt"}, {ID: "gpt-4o-mini-transcribe", Name: "GPT-4o Mini Transcribe", Kind: "stt"}, {ID: "gpt-image-1", Name: "GPT Image 1", Kind: "image"}, {ID: "dall-e-3", Name: "DALL-E 3", Kind: "image"}, {ID: "dall-e-2", Name: "DALL-E 2", Kind: "image"}}},
	"anthropic": {ID: "anthropic", Alias: "anthropic", BaseURL: "https://api.anthropic.com/v1/messages", Format: "claude", Headers: map[string]string{"anthropic-version": "2023-06-01", "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14"}, Services: []string{"llm", "imageToText"}, Models: []Model{{ID: "claude-sonnet-4-20250514", Name: "Claude Sonnet 4"}, {ID: "claude-opus-4-20250514", Name: "Claude Opus 4"}, {ID: "claude-3-5-sonnet-20241022", Name: "Claude 3.5 Sonnet"}}},
	"gemini":    {ID: "gemini", Alias: "gemini", BaseURL: "https://generativelanguage.googleapis.com/v1beta", Format: "gemini", Services: []string{"llm", "embedding", "image", "imageToText", "tts", "stt"}, Models: []Model{{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}, {ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash Lite"}, {ID: "gemini-embedding-001", Name: "Gemini Embedding 001", Kind: "embedding"}, {ID: "gemini-2.5-flash-image", Name: "Gemini 2.5 Flash Image", Kind: "image"}}},
	"codex":     {ID: "codex", Alias: "cx", BaseURL: "https://chatgpt.com/backend-api/codex", Format: "openai-responses", Headers: map[string]string{"originator": "codex_cli_rs", "User-Agent": "codex_cli_rs/0.136.0"}, Services: []string{"llm"}, Models: []Model{{ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}}},
	"github":    {ID: "github", Alias: "gh", BaseURL: "https://api.githubcopilot.com", Format: "openai", Headers: map[string]string{"copilot-integration-id": "vscode-chat", "editor-version": "vscode/1.110.0", "editor-plugin-version": "copilot-chat/0.38.0", "openai-intent": "conversation-panel", "x-github-api-version": "2025-04-01"}, Services: []string{"llm", "embedding"}, Models: []Model{{ID: "gpt-5.4", Name: "GPT-5.4"}, {ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini"}, {ID: "claude-sonnet-4.6", Name: "Claude Sonnet 4.6"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash"}, {ID: "text-embedding-3-small", Name: "Text Embedding 3 Small", Kind: "embedding"}}},
	"vertex":    {ID: "vertex", Alias: "vx", BaseURL: "https://aiplatform.googleapis.com", Format: "vertex", Services: []string{"llm", "imageToText"}, Models: []Model{{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro"}, {ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash"}}},
	"kiro":      {ID: "kiro", Alias: "kiro", BaseURL: "https://runtime.us-east-1.kiro.dev", Format: "kiro", Services: []string{"llm"}, Models: []Model{{ID: "claude-sonnet-4", Name: "Claude Sonnet 4"}, {ID: "claude-3.7-sonnet", Name: "Claude 3.7 Sonnet"}}},
	"cursor":    {ID: "cursor", Alias: "cu", BaseURL: "https://api2.cursor.sh/aiserver.v1.ChatService/StreamUnifiedChatWithTools", Format: "cursor", Headers: map[string]string{"connect-accept-encoding": "gzip", "connect-protocol-version": "1", "content-type": "application/connect+proto", "user-agent": "connect-es/1.6.1"}, Services: []string{"llm"}, Models: []Model{{ID: "default", Name: "Auto (Server Picks)"}, {ID: "claude-4.5-sonnet", Name: "Claude 4.5 Sonnet"}, {ID: "gpt-5.2", Name: "GPT-5.2"}, {ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview"}}},
}

func Lookup(id string) (Descriptor, bool) { descriptor, ok := Registry[id]; return descriptor, ok }
